// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/bridge/node_account.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NodeAccount struct {
	Id                  uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeAddress         []byte     `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	IpAddress           string     `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status              int32      `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	PubKeySet           *PubKeySet `protobuf:"bytes,5,opt,name=pub_key_set,json=pubKeySet,proto3" json:"pub_key_set,omitempty"`
	ValidatorConsPubKey string     `protobuf:"bytes,6,opt,name=validator_cons_pub_key,json=validatorConsPubKey,proto3" json:"validator_cons_pub_key,omitempty"`
	SignerMembership    []string   `protobuf:"bytes,7,rep,name=signer_membership,json=signerMembership,proto3" json:"signer_membership,omitempty"`
}

func (m *NodeAccount) Reset()         { *m = NodeAccount{} }
func (m *NodeAccount) String() string { return proto.CompactTextString(m) }
func (*NodeAccount) ProtoMessage()    {}
func (*NodeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fbd26d9c8820977, []int{0}
}
func (m *NodeAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAccount.Merge(m, src)
}
func (m *NodeAccount) XXX_Size() int {
	return m.Size()
}
func (m *NodeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAccount proto.InternalMessageInfo

func (m *NodeAccount) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeAccount) GetNodeAddress() []byte {
	if m != nil {
		return m.NodeAddress
	}
	return nil
}

func (m *NodeAccount) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *NodeAccount) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NodeAccount) GetPubKeySet() *PubKeySet {
	if m != nil {
		return m.PubKeySet
	}
	return nil
}

func (m *NodeAccount) GetValidatorConsPubKey() string {
	if m != nil {
		return m.ValidatorConsPubKey
	}
	return ""
}

func (m *NodeAccount) GetSignerMembership() []string {
	if m != nil {
		return m.SignerMembership
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeAccount)(nil), "bridge.bridge.NodeAccount")
}

func init() { proto.RegisterFile("bridge/bridge/node_account.proto", fileDescriptor_3fbd26d9c8820977) }

var fileDescriptor_3fbd26d9c8820977 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x9b, 0xed, 0x1f, 0xd9, 0x6c, 0x15, 0x8d, 0x58, 0x82, 0xe0, 0x1a, 0x3d, 0x2d, 0x08,
	0x5b, 0xb0, 0x17, 0xaf, 0xd5, 0xa3, 0x28, 0xb2, 0xde, 0xbc, 0x84, 0xdd, 0x66, 0xa8, 0x41, 0xbb,
	0x09, 0x49, 0x56, 0xec, 0x5b, 0x08, 0xbe, 0x94, 0xc7, 0x1e, 0x3d, 0x4a, 0xfb, 0x22, 0x62, 0xb3,
	0x5d, 0xec, 0x69, 0x92, 0xef, 0x37, 0xf3, 0xcd, 0xf0, 0x61, 0x56, 0x18, 0x29, 0xa6, 0x30, 0xac,
	0x4b, 0xa9, 0x04, 0xf0, 0x7c, 0x32, 0x51, 0x55, 0xe9, 0x52, 0x6d, 0x94, 0x53, 0x64, 0xd7, 0xa3,
	0xd4, 0x97, 0xe3, 0xd3, 0xed, 0x01, 0x5d, 0x15, 0xfc, 0x05, 0xe6, 0xdc, 0x42, 0xdd, 0x7f, 0xfe,
	0x19, 0xe0, 0xe8, 0x5e, 0x09, 0x18, 0x7b, 0x17, 0xb2, 0x87, 0x03, 0x29, 0x28, 0x62, 0x28, 0xe9,
	0x64, 0x81, 0x14, 0xe4, 0x0c, 0xf7, 0xfd, 0x16, 0x21, 0x0c, 0x58, 0x4b, 0x03, 0x86, 0x92, 0x7e,
	0x16, 0xfd, 0x69, 0x63, 0x2f, 0x91, 0x13, 0x8c, 0xa5, 0x6e, 0x1a, 0xda, 0x0c, 0x25, 0x61, 0x16,
	0x4a, 0xbd, 0xc1, 0x03, 0xdc, 0xb3, 0x2e, 0x77, 0x95, 0xa5, 0x1d, 0x86, 0x92, 0x6e, 0x56, 0xff,
	0xc8, 0x15, 0x8e, 0xfe, 0x9d, 0x43, 0xbb, 0x0c, 0x25, 0xd1, 0x25, 0x4d, 0xb7, 0xee, 0x4f, 0x1f,
	0xaa, 0xe2, 0x16, 0xe6, 0x8f, 0xe0, 0xb2, 0x50, 0x6f, 0x9e, 0x64, 0x84, 0x07, 0x6f, 0xf9, 0xab,
	0x14, 0xb9, 0x53, 0x86, 0x4f, 0x54, 0x69, 0x79, 0x6d, 0x44, 0x7b, 0xeb, 0xe5, 0x87, 0x0d, 0xbd,
	0x51, 0xa5, 0xf5, 0x16, 0xe4, 0x02, 0x1f, 0x58, 0x39, 0x2d, 0xc1, 0xf0, 0x19, 0xcc, 0x0a, 0x30,
	0xf6, 0x59, 0x6a, 0xba, 0xc3, 0xda, 0x49, 0x98, 0xed, 0x7b, 0x70, 0xd7, 0xe8, 0xd7, 0xc3, 0xaf,
	0x65, 0x8c, 0x16, 0xcb, 0x18, 0xfd, 0x2c, 0x63, 0xf4, 0xb1, 0x8a, 0x5b, 0x8b, 0x55, 0xdc, 0xfa,
	0x5e, 0xc5, 0xad, 0xa7, 0xa3, 0x3a, 0xc9, 0xf7, 0x4d, 0xa4, 0x6e, 0xae, 0xc1, 0x16, 0xbd, 0x75,
	0x9a, 0xa3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x1a, 0x4b, 0xca, 0xa1, 0x01, 0x00, 0x00,
}

func (m *NodeAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerMembership) > 0 {
		for iNdEx := len(m.SignerMembership) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SignerMembership[iNdEx])
			copy(dAtA[i:], m.SignerMembership[iNdEx])
			i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.SignerMembership[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ValidatorConsPubKey) > 0 {
		i -= len(m.ValidatorConsPubKey)
		copy(dAtA[i:], m.ValidatorConsPubKey)
		i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.ValidatorConsPubKey)))
		i--
		dAtA[i] = 0x32
	}
	if m.PubKeySet != nil {
		{
			size, err := m.PubKeySet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNodeAccount(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintNodeAccount(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.IpAddress) > 0 {
		i -= len(m.IpAddress)
		copy(dAtA[i:], m.IpAddress)
		i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.IpAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintNodeAccount(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintNodeAccount(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNodeAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovNodeAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovNodeAccount(uint64(m.Id))
	}
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	l = len(m.IpAddress)
	if l > 0 {
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovNodeAccount(uint64(m.Status))
	}
	if m.PubKeySet != nil {
		l = m.PubKeySet.Size()
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	l = len(m.ValidatorConsPubKey)
	if l > 0 {
		n += 1 + l + sovNodeAccount(uint64(l))
	}
	if len(m.SignerMembership) > 0 {
		for _, s := range m.SignerMembership {
			l = len(s)
			n += 1 + l + sovNodeAccount(uint64(l))
		}
	}
	return n
}

func sovNodeAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNodeAccount(x uint64) (n int) {
	return sovNodeAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = append(m.NodeAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeAddress == nil {
				m.NodeAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeySet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKeySet == nil {
				m.PubKeySet = &PubKeySet{}
			}
			if err := m.PubKeySet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConsPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConsPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerMembership", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerMembership = append(m.SignerMembership, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNodeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodeAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodeAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNodeAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNodeAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNodeAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNodeAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodeAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNodeAccount = fmt.Errorf("proto: unexpected end of group")
)
